version: 0.2

phases:
  pre_build:
    commands:
       - echo Logging / auth in to Amazon ECR
       - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 488122405204.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started
      - echo Building the docker image
      - docker build -t ecs-fargate-image .
      - docker tag ecs-fargate-image:latest 488122405204.dkr.ecr.us-east-1.amazonaws.com/ecs-fargate-image:latest


  post_build:
    commands:
     - echo build completed
     - echo pushing in to docker ECR...
     - docker push 488122405204.dkr.ecr.us-east-1.amazonaws.com/ecs-fargate-image:latest
     - echo Writing image definition file..
     - printf '[{"name":"%s","imageUri":"%s"}]' "ECS-Fargate-Cluster" "488122405204.dkr.ecr.us-east-1.amazonaws.com/ecs-fargate-image" > imagedefinitions.json


artifacts:
  files:
    - imagedefinitions.json
